--- #sample recipe
variables:
  name: brad
  favourite_colour: red
  age: 345
  drinks_beer: true
  age_and_colour: <%!age%>:<%!favourite_colour%>
  lorumfile: <%f./examples/lorum.txt%>

recipe:
  -  # step0
    name: Call Mockbin # see http://mockbin.org/docs#http-request
    httpmethod: POST
    URL: http://mockbin.org/request/path/to/<%!name%>
    request:
      body:
        name: My name is <%!name%>
        age: I am <%!name%> years old.
        beer_drinker: <%!drinks_beer%>
        lorum_impsum: <%!lorumfile%>
      querystring:
        colors: blue, green,  <%!favourite_colour%>
      headers:
        X-info: <%!age_and_colour%>
  - name: Call Mockbin with data from the previous call.
    httpmethod: GET
    URL: http://mockbin.org/request/path/to/<%!name%>
    request:
      headers:
        date_header_from_previous_call: <%=steps[0].response.headers["Date"]%>
      body:
        http_response_code_from_previous_call: <%=steps[0].response.code%>

