--- #sample recipe
recipe:
  -  # step0
    name: Create Kong API
    httpmethod: GET
    URL: http://kong:8001/apis
    request:
      # body:
      #   name: Consumer API
      #   upstream_uri: http://wiremock/blah
      #   strip_url: false
      headers:
        # Authorisation: yadda-step one authorisation header brad
        Content-type: application/json
      # querystring:
      #   keya: vala
      #   keyb: valb
    response: # set up this response section if you need to pull out data here for use later in the recipe.
      body:
        id: this_is_a_param
      headers:
        Authorisation:
      code:
  -
    name: Load OAUTH Plugin
    httpmethod: GET
    URL: https://wiremock:8081/hello #gets the JSON field id from the body of the response from step 1.
    request:
      body: #TODO: NB!! put in a check for when a body, querystring, or header is defined withot anything below it!
        something: blah
      headers:
        blah: blahbha
    response: # set up this response section if you need to pull out data here for use later in the recipe.
      code:
      body:
      headers:
        Authorisation:
